#!/usr/bin/env php
<?php declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

use kranack\Lint\Commands;

$application = new Application('Lint tools', '0.4.0');

$application->addCommands([
	new Commands\LintFilesCommand(),
	new Commands\InstallCommand(),
]);

$application->run();