#!/usr/bin/env php
<?php declare(strict_types=1);

require_once('require.php');

use Symfony\Component\Console\Application;

use kranack\Lint\Commands;

$application = new Application('Lint tool', '0.5.0');

$application->addCommands([
	new Commands\LintFilesCommand(),
	new Commands\InstallCommand(),
]);

$application->run();