name: Main workflow
on: [push]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Set Composer
      uses: pxgamer/composer-action@master
      with:
        command: install --optimize-autoloader --prefer-dist
    - name: Run install command
      run: ./lint-tool install
    - name: Run lint command
      run: ./lint-tool lint ./src
