name: Main workflow

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set Composer
      uses: pxgamer/composer-action@master
      with:
        command: install --optimize-autoloader --prefer-dist
    - name: Run install command
      run: ./lint-tools install
    - name: Run lint command
      run: ./lint-tools lint ./src
    
